package com.swing.view;

import com.swing.controller.ChuyenManHinh;
import com.swing.obj.DanhMuc;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

public class QLDiem extends javax.swing.JPanel {

    public QLDiem() {
        initComponents();

        ChuyenManHinh controller = new ChuyenManHinh(ContentQLDiem);
        controller.setView(AddDiemLopHoc, AddDiemLopHocLabel, "AddDiemLopHoc");

        List<DanhMuc> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMuc("AddDiemLopHoc", AddDiemLopHoc, AddDiemLopHocLabel));
        listDanhMuc.add(new DanhMuc("UpdateDiemSV", UpdateDiemSV, UpdateDiemSVLabel));
        listDanhMuc.add(new DanhMuc("XemDiemLopHoc", XemDiemLopHoc, XemDiemLopHocLabel));

        controller.setEvent(listDanhMuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabQLDiem = new javax.swing.JPanel();
        UpdateDiemSV = new javax.swing.JPanel();
        UpdateDiemSVLabel = new javax.swing.JLabel();
        AddDiemLopHoc = new javax.swing.JPanel();
        AddDiemLopHocLabel = new javax.swing.JLabel();
        XemDiemLopHoc = new javax.swing.JPanel();
        XemDiemLopHocLabel = new javax.swing.JLabel();
        ContentQLDiem = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TabQLDiem.setBackground(new java.awt.Color(255, 255, 255));

        UpdateDiemSV.setBackground(new java.awt.Color(0, 204, 204));

        UpdateDiemSVLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        UpdateDiemSVLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpdateDiemSVLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/fix.png"))); // NOI18N
        UpdateDiemSVLabel.setText("Sửa điểm sinh viên");

        javax.swing.GroupLayout UpdateDiemSVLayout = new javax.swing.GroupLayout(UpdateDiemSV);
        UpdateDiemSV.setLayout(UpdateDiemSVLayout);
        UpdateDiemSVLayout.setHorizontalGroup(
            UpdateDiemSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDiemSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateDiemSVLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        UpdateDiemSVLayout.setVerticalGroup(
            UpdateDiemSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDiemSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateDiemSVLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        AddDiemLopHoc.setBackground(new java.awt.Color(0, 204, 204));

        AddDiemLopHocLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        AddDiemLopHocLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddDiemLopHocLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/addCourse.png"))); // NOI18N
        AddDiemLopHocLabel.setText("Thêm điểm cho lớp");

        javax.swing.GroupLayout AddDiemLopHocLayout = new javax.swing.GroupLayout(AddDiemLopHoc);
        AddDiemLopHoc.setLayout(AddDiemLopHocLayout);
        AddDiemLopHocLayout.setHorizontalGroup(
            AddDiemLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDiemLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddDiemLopHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddDiemLopHocLayout.setVerticalGroup(
            AddDiemLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDiemLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddDiemLopHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        XemDiemLopHoc.setBackground(new java.awt.Color(0, 204, 204));

        XemDiemLopHocLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        XemDiemLopHocLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XemDiemLopHocLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/class.png"))); // NOI18N
        XemDiemLopHocLabel.setText("Xem điểm lớp học");

        javax.swing.GroupLayout XemDiemLopHocLayout = new javax.swing.GroupLayout(XemDiemLopHoc);
        XemDiemLopHoc.setLayout(XemDiemLopHocLayout);
        XemDiemLopHocLayout.setHorizontalGroup(
            XemDiemLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemDiemLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XemDiemLopHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        XemDiemLopHocLayout.setVerticalGroup(
            XemDiemLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemDiemLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XemDiemLopHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabQLDiemLayout = new javax.swing.GroupLayout(TabQLDiem);
        TabQLDiem.setLayout(TabQLDiemLayout);
        TabQLDiemLayout.setHorizontalGroup(
            TabQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabQLDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddDiemLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateDiemSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(XemDiemLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabQLDiemLayout.setVerticalGroup(
            TabQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabQLDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XemDiemLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateDiemSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDiemLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentQLDiem.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout ContentQLDiemLayout = new javax.swing.GroupLayout(ContentQLDiem);
        ContentQLDiem.setLayout(ContentQLDiemLayout);
        ContentQLDiemLayout.setHorizontalGroup(
            ContentQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContentQLDiemLayout.setVerticalGroup(
            ContentQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabQLDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContentQLDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TabQLDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentQLDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDiemLopHoc;
    private javax.swing.JLabel AddDiemLopHocLabel;
    private javax.swing.JPanel ContentQLDiem;
    private javax.swing.JPanel TabQLDiem;
    private javax.swing.JPanel UpdateDiemSV;
    private javax.swing.JLabel UpdateDiemSVLabel;
    private javax.swing.JPanel XemDiemLopHoc;
    private javax.swing.JLabel XemDiemLopHocLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
