package com.swing.view;

import com.swing.controller.ChuyenManHinh;
import com.swing.obj.DanhMuc;
import java.util.ArrayList;
import java.util.List;

public class QLLopHoc extends javax.swing.JPanel {

    /** Creates new form QLLopHoc */
    public QLLopHoc() {
        initComponents();

        ChuyenManHinh controller = new ChuyenManHinh(ContentQLLopHoc);
        // controller.setView(TrangChu, TrangChuLabel);

        List<DanhMuc> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMuc("AddLopHoc", AddLopHoc, AddLopHocLabel));
        listDanhMuc.add(new DanhMuc("AddSinhVien", AddSinhVien, AddSinhVienLabel));
        listDanhMuc.add(new DanhMuc("XemDSLop", XemDSLop, XemDSLopLabel));

        controller.setEvent(listDanhMuc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabQLLopHoc = new javax.swing.JPanel();
        AddSinhVien = new javax.swing.JPanel();
        AddSinhVienLabel = new javax.swing.JLabel();
        AddLopHoc = new javax.swing.JPanel();
        AddLopHocLabel = new javax.swing.JLabel();
        XemDSLop = new javax.swing.JPanel();
        XemDSLopLabel = new javax.swing.JLabel();
        ContentQLLopHoc = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TabQLLopHoc.setBackground(new java.awt.Color(255, 255, 255));

        AddSinhVien.setBackground(new java.awt.Color(0, 204, 204));

        AddSinhVienLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        AddSinhVienLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddSinhVienLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/AddSinhVien.png"))); // NOI18N
        AddSinhVienLabel.setText("Thêm sinh viên");

        javax.swing.GroupLayout AddSinhVienLayout = new javax.swing.GroupLayout(AddSinhVien);
        AddSinhVien.setLayout(AddSinhVienLayout);
        AddSinhVienLayout.setHorizontalGroup(
            AddSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddSinhVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddSinhVienLayout.setVerticalGroup(
            AddSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddSinhVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        AddLopHoc.setBackground(new java.awt.Color(0, 204, 204));

        AddLopHocLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        AddLopHocLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddLopHocLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/AddLop.png"))); // NOI18N
        AddLopHocLabel.setText("Thêm danh sách lớp");

        javax.swing.GroupLayout AddLopHocLayout = new javax.swing.GroupLayout(AddLopHoc);
        AddLopHoc.setLayout(AddLopHocLayout);
        AddLopHocLayout.setHorizontalGroup(
            AddLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddLopHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddLopHocLayout.setVerticalGroup(
            AddLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddLopHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        XemDSLop.setBackground(new java.awt.Color(0, 204, 204));

        XemDSLopLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        XemDSLopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XemDSLopLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/danhSach.png"))); // NOI18N
        XemDSLopLabel.setText("Xem danh sách lớp");

        javax.swing.GroupLayout XemDSLopLayout = new javax.swing.GroupLayout(XemDSLop);
        XemDSLop.setLayout(XemDSLopLayout);
        XemDSLopLayout.setHorizontalGroup(
            XemDSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemDSLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XemDSLopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        XemDSLopLayout.setVerticalGroup(
            XemDSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemDSLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XemDSLopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabQLLopHocLayout = new javax.swing.GroupLayout(TabQLLopHoc);
        TabQLLopHoc.setLayout(TabQLLopHocLayout);
        TabQLLopHocLayout.setHorizontalGroup(
            TabQLLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabQLLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(XemDSLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabQLLopHocLayout.setVerticalGroup(
            TabQLLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabQLLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabQLLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XemDSLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentQLLopHoc.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout ContentQLLopHocLayout = new javax.swing.GroupLayout(ContentQLLopHoc);
        ContentQLLopHoc.setLayout(ContentQLLopHocLayout);
        ContentQLLopHocLayout.setHorizontalGroup(
            ContentQLLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContentQLLopHocLayout.setVerticalGroup(
            ContentQLLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabQLLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContentQLLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TabQLLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentQLLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddLopHoc;
    private javax.swing.JLabel AddLopHocLabel;
    private javax.swing.JPanel AddSinhVien;
    private javax.swing.JLabel AddSinhVienLabel;
    private javax.swing.JPanel ContentQLLopHoc;
    private javax.swing.JPanel TabQLLopHoc;
    private javax.swing.JPanel XemDSLop;
    private javax.swing.JLabel XemDSLopLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
