package com.swing.view;

import com.swing.controller.ChuyenManHinh;
import com.swing.obj.DanhMuc;
import java.util.ArrayList;
import java.util.List;

public class QLMonHoc extends javax.swing.JPanel {

    public QLMonHoc() {
        initComponents();
        
        ChuyenManHinh controller = new ChuyenManHinh(ContentQLMonHoc);
        controller.setView(DangKyMonHoc, DangKyMonHocLabel, "DangKyMonHoc");

        List<DanhMuc> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMuc("DangKyMonHoc", DangKyMonHoc, DangKyMonHocLabel));
        listDanhMuc.add(new DanhMuc("HuyMonHoc", HuyMonHoc, HuyMonHocLabel));

        controller.setEvent(listDanhMuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabQLMonHoc = new javax.swing.JPanel();
        HuyMonHoc = new javax.swing.JPanel();
        HuyMonHocLabel = new javax.swing.JLabel();
        DangKyMonHoc = new javax.swing.JPanel();
        DangKyMonHocLabel = new javax.swing.JLabel();
        ContentQLMonHoc = new javax.swing.JPanel();

        HuyMonHoc.setBackground(new java.awt.Color(0, 204, 204));

        HuyMonHocLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        HuyMonHocLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HuyMonHocLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/delCourse.png"))); // NOI18N
        HuyMonHocLabel.setText("Huỷ đăng ký môn học ");

        javax.swing.GroupLayout HuyMonHocLayout = new javax.swing.GroupLayout(HuyMonHoc);
        HuyMonHoc.setLayout(HuyMonHocLayout);
        HuyMonHocLayout.setHorizontalGroup(
            HuyMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuyMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HuyMonHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        HuyMonHocLayout.setVerticalGroup(
            HuyMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuyMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HuyMonHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        DangKyMonHoc.setBackground(new java.awt.Color(0, 204, 204));

        DangKyMonHocLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        DangKyMonHocLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DangKyMonHocLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swing/images/addCourse.png"))); // NOI18N
        DangKyMonHocLabel.setText("Đăng ký môn học");

        javax.swing.GroupLayout DangKyMonHocLayout = new javax.swing.GroupLayout(DangKyMonHoc);
        DangKyMonHoc.setLayout(DangKyMonHocLayout);
        DangKyMonHocLayout.setHorizontalGroup(
            DangKyMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangKyMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DangKyMonHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        DangKyMonHocLayout.setVerticalGroup(
            DangKyMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangKyMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DangKyMonHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabQLMonHocLayout = new javax.swing.GroupLayout(TabQLMonHoc);
        TabQLMonHoc.setLayout(TabQLMonHocLayout);
        TabQLMonHocLayout.setHorizontalGroup(
            TabQLMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabQLMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DangKyMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HuyMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        TabQLMonHocLayout.setVerticalGroup(
            TabQLMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabQLMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabQLMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HuyMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DangKyMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentQLMonHocLayout = new javax.swing.GroupLayout(ContentQLMonHoc);
        ContentQLMonHoc.setLayout(ContentQLMonHocLayout);
        ContentQLMonHocLayout.setHorizontalGroup(
            ContentQLMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContentQLMonHocLayout.setVerticalGroup(
            ContentQLMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabQLMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContentQLMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TabQLMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentQLMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentQLMonHoc;
    private javax.swing.JPanel DangKyMonHoc;
    private javax.swing.JLabel DangKyMonHocLabel;
    private javax.swing.JPanel HuyMonHoc;
    private javax.swing.JLabel HuyMonHocLabel;
    private javax.swing.JPanel TabQLMonHoc;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
